apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
spec:
  accessModes:
    - {{ .Values.database.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.resourcesRequestsStorage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
        - name: {{ .Values.database.image.name }}
          image: {{ .Values.database.image.name }}:{{ .Values.database.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Values.env.config }}
            - secretRef:
                name: {{ .Values.env.secrets }}
          ports:
            - containerPort: {{ .Values.database.ports.containerPort }}
          volumeMounts:
            - name: {{ .Values.database.volumeMounts.name }}
              mountPath: {{ .Values.database.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Values.database.volumeMounts.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.database.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.database.ports.containerPort }}
      targetPort: {{ .Values.database.ports.containerPort }}
  selector:
    app: {{ .Values.database.name }}
  clusterIP: None
